name: Run Prettier Check
on:
    workflow_dispatch:
    pull_request:
        branches: [main, develop]
jobs:
    prettier:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Prettier Action
              uses: creyD/prettier_action@v4.3
              with:
                  prettier_options: --check **/*.{js,md}
